version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: gamecraft-postgres
    environment:
      POSTGRES_DB: gamecraft_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gamecraft-network

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: gamecraft-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gamecraft-network

  # Spring Boot 애플리케이션 (선택사항)
  app:
    build: .
    container_name: gamecraft-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - gamecraft-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
  redis_data:

networks:
  gamecraft-network:
    driver: bridge