spring:
  profiles:
    active: dev
  application:
    name: GameCraft Studios Backend

  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/gamecraft_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate 설정 (PostgreSQL 전용)
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발시: create-drop, 운영시: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # OAuth2 설정 (카카오)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:YOUR_KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET:YOUR_KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# GitHub API 설정
github:
  api:
    token: ${GITHUB_TOKEN:}  # 환경변수로 설정 (옵션)
    base-url: https://api.github.com
    timeout: 5000

server:
  port: 8080

# JWT 설정
jwt:
  secret: ${JWT_SECRET:gamecraft-studios-jwt-secret-key-for-kakao-games-2025-must-be-at-least-32-characters-long}
  expiration: 86400000  # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.gamecraft.studios: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE